apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: cloudflare
  labels:
    app: cloudflared
    app.kubernetes.io/component: network
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/part-of: home-assistant
type: Opaque
stringData:
  credentials.json: |
    { "AccountTag":"","TunnelSecret":"","TunnelID":"","Endpoint":""}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
  labels:
    app: cloudflared
    app.kubernetes.io/component: network
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/part-of: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        imagePullPolicy: Always
        args:
        - tunnel
        - --protocol
        - http2
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      volumes:
      - name: config
        configMap:
          name: cloudflared-config
          items:
          - key: config.yaml
            path: config.yaml
      - name: creds
        secret:
          secretName: cloudflared-credentials
          items:
          - key: credentials.json
            path: credentials.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
  labels:
    app: cloudflared
    app.kubernetes.io/component: network
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/part-of: home-assistant
data:
  config.yaml: |
    tunnel: 0a211d06-
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: home-assistant.dev
      service: http://home-assistant.home-assistant.svc.cluster.local
    - service: http_status:404
