apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: semaphore
  name: semaphore-core-pvc
  namespace: semaphore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

