apiVersion: v1
kind: Service
metadata:
  labels:
    service: semaphore
  name: semaphore
  namespace: semaphore
spec:
  ports:
    - name: ui
      port: 3000
      targetPort: 3000
  selector:
    service: semaphore

