kind: ConfigMap
apiVersion: v1
metadata:
  name: ha-india-configmap
  namespace: ha-india
data:
  known_devices.yaml: |
  automations.yaml: |
  configuration.yaml: |-
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/16
        - 127.0.0.1
        - 0.0.0.0/0
    # ble_monitor:
    #   bt_interface: 'A4:6B:B6:06:AC:A1'
    #   bt_auto_restart: False
    #   active_scan: False
    #   discovery: True
    #   period: 60
    #   use_median: False
    #   decimals: 1
    #   log_spikes: False
    #   restore_state: False
      report_unknown: False
   # mqtt:
   #    discovery: true
   #    discovery_prefix: homeassistant
   #    sensor:
   #      - name: "MiFlora Temperature"
   #        state_topic: "homeassistant/sensor/mint"
           
      #sensor:
      #  - platform: mqtt
      #   name: MiFlora
      #   monitored_conditions:
      #     - moisture
      #     - light
      #     - temperature
      #     - conductivity
      #   state_topic: "homeassistant/sensor/mint/state"
      #   unit_of_measurement:
      #     moisture: '%'
      #     light: 'lux'
      #     temperature: '°C'
      #     conductivity: 'µS/cm'
      #   value_template: '{{ value_json.moisture }}'
      #   json_attributes_topic: "homeassistant/sensor/mint/state"
      #   json_attributes_template: '{{ value_json | tojson }}'

