---
apiVersion: v1
kind: Namespace
metadata:
  name: ha-test
---
apiVersion: v1
kind: Service
metadata:
  namespace: ha-test
  name: ha-test
spec:
  selector:
    app: ha-test
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ha-test
  name: ha-test
  labels:
    app: ha-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ha-test
  template:
    metadata:
      labels:
        app: ha-test
    spec:
      containers:
      # - name: bluez
      #   image: ghcr.io/mysticrenji/bluez-service:v1
      #   securityContext:
      #     privileged: true
      - name: ha-test
        image: homeassistant/home-assistant:2025.5.2
#        resources:
#          requests:
#            memory: "1Gi"
#          limits:
#            memory: "1.5Gi"
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /config/configuration.yaml
          subPath: configuration.yaml
          name:  ha-test-configmap
        - mountPath: /config/automations.yaml
          subPath: automations.yaml
          name:  ha-test-configmap
        # - mountPath: /dev/ttyUSB1
        #   name: zigbee
        securityContext:
          privileged: true
          # capabilities:
          #   add:
          #     - NET_ADMIN
          #     - NET_RAW
          #     - SYS_ADMIN
      hostNetwork: true
      # nodeSelector:
      #   workload: india
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: ha-test-pvc
      - name:  ha-test-configmap
        configMap:
          name: ha-test-configmap
      # - name: zigbee
      #   hostPath:
      #     path: /dev/ttyACM0
---
apiVersion: v1
kind: Service
metadata:
  namespace: ha-test
  name: zwavejs2mqtt
spec:
  selector:
    app: zwavejs2mqtt
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8091
    targetPort: 8091
  - name: ws
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ha-test
  name: zwavejs2mqtt-india
  labels:
    app: zwavejs2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zwavejs2mqtt
  template:
    metadata:
      labels:
        app: zwavejs2mqtt
    spec:
      # restartPolicy: OnFailure 
      containers:
      - name: zwavejs2mqtt
        image: zwavejs/zwavejs2mqtt:10.5.1
        ports:
        - containerPort: 8091
        - containerPort: 3000
        volumeMounts:
        - mountPath: /usr/src/app/store
          name: configuration
        # - mountPath: /dev/ttyACM0
        #   name: zwave
        securityContext:
          privileged: true
      volumes:
      - name: configuration
        persistentVolumeClaim:
            claimName: zwavejs2mqtt-india-pvc
      # - name: zwave
      #   hostPath:
      #     path: /dev/ttyACM0
      # nodeSelector:
      #   workload: india
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: ha-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: arm64v8/eclipse-mosquitto
        securityContext:
          privileged: true
        ports:
        - containerPort: 1883
        - containerPort: 9001
      #nodeSelector:
      #  workload: india
---
apiVersion: v1
kind: Service
metadata:
  namespace: ha-test
  name: mosquitto-service
spec:
  selector:
    app: mosquitto-service
  type: ClusterIP
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: mqtt1
    protocol: TCP
    port: 9001
    targetPort: 9001        

