apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: edgeblazer-cert
  namespace: ingress-nginx
spec:
  secretName: edgeblazer-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - edgeblazer.io
