name: Docker Build for Bluez Service
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

  pull_request:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Get TAG
        id: get_tag
        run: echo TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./home-automation/ble
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            Version=${{  env.TAG }}
            GitCommit=${{ github.sha }}
          tags: |
              ghcr.io/${{ github.repository_owner }}/bluez-service:latest
              ghcr.io/${{ github.repository_owner }}/bluez-service:${{ github.sha }}
              ghcr.io/${{ github.repository_owner}}/bluez-service:${{ env.TAG }}
          secrets: |
              GIT_AUTH_TOKEN=${{ secrets.TOKEN }}
          